spring:
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB
 jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: Asia/Shanghai
 application:
  name: BlogBackend
 shell:
  interactive:
   enabled: true
 data:
  redis:
   host: 127.0.0.1
   port: 6379
   database: 0
 datasource:
  url: jdbc:postgresql://123.0.0.1:5432/pg
  username: pg
  password: 123456
  driverClassName: org.postgresql.Driver
server:
 address: 0.0.0.0
 port: 8102
springdoc:
 swagger-ui:
  enabled: true
mybatis-flex:
 global-config:
  logic-delete-column: available
website: "http://localhost:3000"
common:
 tencent:
  secretId: "123"
  secretKey: "123"
 captcha:
  captchaAppId: "123"
  appSecretKey: "234"
  enable: true
 aliyun:
  secretId: "123"
  secretKey: "123"
 sms:
  signName: xx商城
  templateCode: SMS_1xxxxz
 github:
  clientId: "123"
  clientSecret: "123"
  redirectUri: "http://localhost:8102/oauth/github/callback"
  enable: true
 qq:
  clientId: "123"
  clientSecret: "123"
  redirectUri: "http://localhost:3000"
  enable: false
 alist:
  path: ""
