spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  application:
    name: BlogBackend
  shell:
    interactive:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    url: jdbc:postgresql://123.0.0.1:5432/pg
    username: pg
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  address: 0.0.0.0
  port: 8102
springdoc:
  swagger-ui:
    enabled: true
mybatis-flex:
  global-config:
    logic-delete-column: available
common:
  tencent:
    secretId: "123"
    secretKey: "123"
    captcha:
      captchaAppId: "123"
      appSecretKey: "234"
      enable: true
  aliyun:
    secretId: "123"
    secretKey: "123"
  sms:
    signName: xx商城
    templateCode: SMS_1xxxx