spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  application:
    name: BlogBackend
  shell:
    interactive:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    url: jdbc:postgresql://123.0.0.1:5432/pg
    username: pg
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  address: 0.0.0.0
  port: 8102
springdoc:
  swagger-ui:
    enabled: true
common:
  tencent:
    secretId: "123"
    secretKey: "123"
  captcha:
    captchaAppId: "123"
    appSecretKey: "234"
    enable: true
  sms:
    secretId: "你的SecretId"
    secretKey: "你的SecretKey"
    smsSdkAppId: "1400000000" # 腾讯云短信应用ID
    signName: "你的短信签名"
    templateId: "123456" # 你在腾讯云配置的短信模板ID
  account:
    captchaEnable: true
    registerEnable: true
    forgetEnable: true
    inviteEnable: true