spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  application:
    name: BlogBackend
  shell:
    interactive:
      enabled: true
  data:
    redis:
      host: 118.178.138.202
      port: 6379
      database: 0
  datasource:
    url: jdbc:postgresql://118.178.138.202/postgres
    username: pg
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  address: 0.0.0.0
  port: 8102
springdoc:
  swagger-ui:
    enabled: true